import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // ✅ 공식 Script 컴포넌트 import
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "카카오 지도 테스트",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ 카카오 지도 스크립트 로딩 (권장 방식) */}
        <Script
          src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=fe0ceddbeea976ed8c1b8cfdf453c747&autoload=false&libraries=services"
          strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
